spring:
  datasource:
    url: jdbc:postgresql://task-postgres/taskdb_activity
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://task-keycloak/realms/TaskAgile
  rabbitmq:
    host: task-rabbitmq